name: PMS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        msbuild pms.Android/pms.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        sudo xcode-select --switch /Applications/Xcode_11.4.app/Contents/Developer
        msbuild pms.iOS/pms.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
